config/routes.rb
Rails.application.routes.draw do
  # resources :services
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "users#profile"
  # get "/pending_orders", to: "sales#show_pending_orders"
  get "/pending_sales", to: "sales#show_pending_sales"
  get "myorders", to: "sales#my_orders"
  patch "sales/:id", to: "sales#update_status", as: "update_status"
  # get "/services/:id", to: "services#show"
  # post "services/:service_id/sales", to: "sales#create"
  get "/user_services", to: "services#user_services"
  # get "/services/new", to: "services#new"
  # get "services:id/edit", to: "services#edit"
  resources :services, only: %i[index new create edit update destroy show] do
    resources :sales, only: %i[new create]
  end
  resources :sales, only: %i[edit show]

  resources :users, only: %i[show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users/languages/new", to: "users#new_language", as: :new_language
  post "/languages", to: "users#create_language"
  get "edit_language/:language_id", to: "users#edit_language", as: :edit_language
  patch "update_language/:language_id", to: "users#update_language", as: :update_language
  delete "destroy_language/:language_id", to: "users#destroy_language", as: "destroy_language"

  get "/users/skills/new", to: "users#new_skill", as: :new_skill
  post "/skills", to: "users#create_skill"
  get "edit_skill/:skill_id", to: "users#edit_skill", as: :edit_skill
  patch "update_skill/:skill_id", to: "users#update_skill", as: :update_skill
  delete "destroy_skill/:skill_id", to: "users#destroy_skill", as: "destroy_skill"

  get "/users/educations/new", to: "users#new_education", as: :new_education
  post "/educations", to: "users#create_education"
  get "edit_education/:education_id", to: "users#edit_education", as: :edit_education
  patch "update_education/:education_id", to: "users#update_education", as: :update_education
  delete "destroy_education/:education_id", to: "users#destroy_education", as: "destroy_education"

  get "/users/certifications/new", to: "users#new_certification", as: :new_certification
  post "/certifications", to: "users#create_certification"
  get "edit_certification/:certification_id", to: "users#edit_certification", as: :edit_certification
  patch "update_certification/:certification_id", to: "users#update_certification", as: :update_certification
  delete "destroy_certification/:certification_id", to: "users#destroy_certification", as: "destroy_certification"
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :sales, dependent: :destroy
  has_many_attached :images

  include PgSearch::Model
  pg_search_scope :search_by_service,
  against: [ :title, :description, :category ],
  using: {
    tsearch: { prefix: true }
  }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:search].present?
      @services = Service.search_by_service(params[:search])
    else
      @services = Service.all
    end
  end

  def show
    @seller = @service.user
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to service_path(@service)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @service.update(service_params)
      redirect_to service_path(@service)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @service.destroy
    redirect_to user_services_path
  end

  def user_services
    @user_services = Service.where(user: current_user)
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :price, :category, :delivery_time, images: [])
  end
end

app/views/services/_form.html.erb
  <%= simple_form_for(@service) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :category, collection: ["content-writing", "landing-page", "back-end", "front-end", "e-commerce", "mobile-development", "graphic-design", "digital-marketing", "social-media", "video-creation"] %>
  <%= f.input :delivery_time %>
  <%= f.input :images, as: :file, input_html: { multiple: true } %>
  <%= f.submit%>
<% end %>

app/views/services/edit.html.erb
<div class="container d-flex justify-content-center mt-5 pt-5">
  <div class="edit card text-bg-light rounded-4">
    <div class="py-2", style="color: white"><h2>Edit the service</h2></div>
      <%= render "form" %>
  </div>
</div>

app/views/services/index.html.erb
<div class="container mt-5">
  <h1>Here all our Services</h1>
  <p>You can consult them in the below list</p>
</div>

<div class="container mt-2">
  <div class="d-grid" style="grid-template-columns: 1fr 1fr 1fr;">
      <% @services.each do |service| %>
        <div class="col m-2">
          <div class="service-card h-100" style="width: 18rem;">
          <% if service.images.first %>
            <%= cl_image_tag service.images.first.key %>
          <% else %>
            <%= image_tag("image_default.jpg") %>
          <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= service.title %></h5>
              <%= link_to "Details", service_path(service), class: "btn-main mt-auto" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/services/new.html.erb
<div class="container d-flex justify-content-center my-5 py-5">
  <div class="new card text-bg-light rounded-4">
    <div class="py-2", style="color: white"><h2>Add a new service</h2></div>
  <%= render "form" %>
  </div>
</div>
</div>

app/views/services/show.html.erb
<div class="container">
  <div class="container d-flex justify-content-between align-items-center mt-5 seller-bar">
    <div>
      <% if @seller.photo.attached? %>
            <%= cl_image_tag @seller.photo.key, class:"avatar" %>
        <% else %>
            <%= image_tag("avatar_default.png", class: "avatar mx-2") %>
      <% end %>
      <%= @seller.first_name %> <%= @seller.last_name %>
    </div>
    <div>
      <% if @seller == current_user %>
          <%= link_to "See my profile", profile_path, class: "btn-main" %>
            <% else %>
          <%= link_to "See profile", user_path(@service.user), class: "btn-main" %>
      <% end %>

    </div>
  </div>
    <div class="container mt-5">
      <h1><%= @service.title %></h1>
    </div>
    <div class="container d-flex mt-5">
      <div class="main-image">
      <% if @service.images.attached? %>
        <%= cl_image_tag @service.images.first.key, class: "service-image main" %>
      </div>
      <div class="container other-images">
        <div class="row">
        <% @service.images.drop(1).each do |image| %>
        <div class="col other-image">
          <%= cl_image_tag image.key, class: "service-image other" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

  <div class="container description mt-5">
    <h2>Description</h2>
    <div class="description-bar mt-5">
    <p><%= @service.description %></p>
    </div>
  </div>


<!-- Modal -->
<div class="modal purchase-modal fade" id="PurchaseModal" tabindex="-1" aria-labelledby="PurchaseModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="PurchaseModal">You are completing your purchase for:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><%= @service.title %></p>
        <p>Price: <%= @service.price %>€</p>
      </div>
      <div class="modal-footer">
          <%= button_to "Confirm Purchase", service_sales_path(@service), class: "btn-alternative" %>
      </div>
    </div>
  </div>
</div>

<div class="container d-flex justify-content-between align-items-center purchase-bar">
  <div class="price">
    <p>Price: <%= @service.price %>€</p>
  </div>
  <div class="buy-button">
  <% if @seller == current_user %>
    <% elsif user_signed_in? %>
    <button type="button" class="btn-main" data-bs-toggle="modal" data-bs-target="#PurchaseModal">Buy</button>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn-main" %>
    <% end %>
  </div>
</div>
</div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/services/user_services.html.erb
<div class="container my-4 pt-5">
  <div class="container d-flex justify-content-between mb-5">
    <h1>Here all your services</h1>
    <button class="btn-alternative"><%= link_to "Show pending sales", pending_sales_path %></button>
    <button class="btn-alternative"><%= link_to "Create a new service", new_service_path %></button>
  </div>
  <table class="table table-striped table-dark custom-table">
    <thead>
      <tr>
        <th scope="col"style="width: 10%"></th>
        <th scope="col" style="width: 20%">Title</th>
        <th scope="col" style="width: 50%">Description</th>
        <th scope="col" style="width: 20%">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @user_services.each_with_index do |service, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= link_to service.title, service_path(service), class: "text-decoration-none text-light" %></td>
          <td><%= service.description %></td>
          <td>
          <div class="d-flex justify-content-center">
          <button class="btn-edit"><%= link_to "Edit", edit_service_path(service)%></button>
          <button class="btn-delete"><%= link_to "Delete", service_path(service), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></button>
          </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>