config/routes.rb
Rails.application.routes.draw do
  # resources :services
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "users#profile"
  # get "/pending_orders", to: "sales#show_pending_orders"
  get "/pending_sales", to: "sales#show_pending_sales"
  get "myorders", to: "sales#my_orders"
  patch "sales/:id", to: "sales#update_status", as: "update_status"
  # get "/services/:id", to: "services#show"
  # post "services/:service_id/sales", to: "sales#create"
  get "/user_services", to: "services#user_services"
  # get "/services/new", to: "services#new"
  # get "services:id/edit", to: "services#edit"
  resources :services, only: %i[index new create edit update destroy show] do
    resources :sales, only: %i[new create]
  end
  resources :sales, only: %i[edit show]

  resources :users, only: %i[show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users/languages/new", to: "users#new_language", as: :new_language
  post "/languages", to: "users#create_language"
  get "edit_language/:language_id", to: "users#edit_language", as: :edit_language
  patch "update_language/:language_id", to: "users#update_language", as: :update_language
  delete "destroy_language/:language_id", to: "users#destroy_language", as: "destroy_language"

  get "/users/skills/new", to: "users#new_skill", as: :new_skill
  post "/skills", to: "users#create_skill"
  get "edit_skill/:skill_id", to: "users#edit_skill", as: :edit_skill
  patch "update_skill/:skill_id", to: "users#update_skill", as: :update_skill
  delete "destroy_skill/:skill_id", to: "users#destroy_skill", as: "destroy_skill"

  get "/users/educations/new", to: "users#new_education", as: :new_education
  post "/educations", to: "users#create_education"
  get "edit_education/:education_id", to: "users#edit_education", as: :edit_education
  patch "update_education/:education_id", to: "users#update_education", as: :update_education
  delete "destroy_education/:education_id", to: "users#destroy_education", as: "destroy_education"

  get "/users/certifications/new", to: "users#new_certification", as: :new_certification
  post "/certifications", to: "users#create_certification"
  get "edit_certification/:certification_id", to: "users#edit_certification", as: :edit_certification
  patch "update_certification/:certification_id", to: "users#update_certification", as: :update_certification
  delete "destroy_certification/:certification_id", to: "users#destroy_certification", as: "destroy_certification"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sales
  has_many :services
  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_language, only: [:edit_language, :update_language, :destroy_language]
  before_action :set_user_skill, only: [:edit_skill, :update_skill, :destroy_skill]
  before_action :set_user_education, only: [:edit_education, :update_education, :destroy_education]
  before_action :set_user_certification, only: [:edit_certification, :update_certification, :destroy_certification]

  def profile
    @user_languages = UserLanguage.where(user: current_user)
    @user_skills = UserSkill.where(user: current_user)
    @user_educations = UserEducation.where(user: current_user)
    @user_certifications = UserCertification.where(user: current_user)
    @user_services = current_user.services
  end

  def new_language
    @user_language = UserLanguage.new
  end

  def create_language
    @user_language = UserLanguage.find_by(language: params[:user_language][:language].downcase)
    unless @user_language
      @user_language = UserLanguage.new(language_params)
      @user_language.language = @user_language.language.downcase
    end
    @user_language.user = current_user
    if @user_language.save!
      redirect_to profile_path, notice: "Language added succesfully"
    else
      render :new_language, status: :unprocessable_entity
    end
  end

  def edit_language
  end

  def update_language
    if @user_language.update(language_params)
      redirect_to profile_path, notice: 'Language was successfully updated.'
    else
      render :edit_language
    end
  end

  def destroy_language
    @user_language.destroy
    redirect_to profile_path, notice: 'Language was successfully deleted.'
  end

  def new_skill
    @user_skill = UserSkill.new
  end

  def create_skill
    @user_skill = UserSkill.new(skill_params)
    @user_skill.user = current_user
    if @user_skill.save!
      redirect_to profile_path, notice: "Skill added succesfully"
    else
      render :new_skill, status: :unprocessable_entity
    end
  end

  def edit_skill
  end

  def update_skill
    if @user_skill.update(skill_params)
      redirect_to profile_path, notice: 'Skill was successfully updated.'
    else
      render :edit_skill
    end
  end

  def destroy_skill
    @user_skill.destroy
    redirect_to profile_path, notice: 'Skill was successfully deleted.'
  end

  def new_education
    @user_education = UserEducation.new
  end

  def create_education
    @user_education = UserEducation.new(education_params)
    @user_education.user = current_user
    if @user_education.save!
      redirect_to profile_path, notice: "Education created succesfully"
    else
      render :new_education, status: :unprocessable_entity
    end
  end

  def edit_education
  end

  def update_education
    if @user_education.update(education_params)
      redirect_to profile_path, notice: 'Education was successfully updated.'
    else
      render :edit_education
    end
  end

  def destroy_education
    @user_education.destroy
    redirect_to profile_path, notice: 'Education was successfully deleted.'
  end

  def new_certification
    @user_certification = UserCertification.new
  end

  def create_certification
    @user_certification = UserCertification.new(certification_params)
    @user_certification.user = current_user
    if @user_certification.save!
      redirect_to profile_path, notice: "Certification created succesfully"
    else
      render :new_certification, status: :unprocessable_entity
    end
  end

  def edit_certification
  end

  def update_certification
    if @user_certification.update(certification_params)
      redirect_to profile_path, notice: 'Certification was successfully updated.'
    else
      render :edit_certification
    end
  end

  def destroy_certification
    @user_certification.destroy
    redirect_to profile_path, notice: 'Certification was successfully deleted.'
  end

  def show
    @user = User.find(params[:id])
    @user_languages = UserLanguage.where(user: @user)
    @user_skills = UserSkill.where(user: @user)
    @user_educations = UserEducation.where(user: @user)
    @user_certifications = UserCertification.where(user: @user)
    @user_services = @user.services
  end

  private

  def set_user_language
    @user_language = UserLanguage.find(params[:language_id])
  end

  def language_params
    params.require(:user_language).permit(:language, :level)
  end

  def set_user_skill
    @user_skill = UserSkill.find(params[:skill_id])
  end

  def skill_params
    params.require(:user_skill).permit(:skill, :level)
  end

  def set_user_education
    @user_education = UserEducation.find(params[:education_id])
  end

  def education_params
    params.require(:user_education).permit(:country, :college, :title, :major, :year)
  end

  def set_user_certification
    @user_certification = UserCertification.find(params[:certification_id])
  end

  def certification_params
    params.require(:user_certification).permit(:certification, :company, :year)
  end
end

app/views/users/edit_certification.html.erb
<div class="container mt-5 pt-5">
  <h2>Edit certification</h2>
  <%= simple_form_for @user_certification, url: update_certification_path(certification_id: @user_certification.id), method: :patch do |f| %>
    <%= f.input :certification %>
    <%= f.input :company %>
    <%= f.input :year %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit_education.html.erb
<div class="container mt-5 pt-5">
  <h2>Edit education</h2>
  <%= simple_form_for @user_education, url: update_education_path(education_id: @user_education.id), method: :patch do |f| %>
    <%= f.input :country, as: :string %>
    <%= f.input :college %>
    <%= f.input :title %>
    <%= f.input :major %>
    <%= f.input :year %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit_language.html.erb
<div class="container mt-5 pt-5">
  <h2>Edit language</h2>
  <%= simple_form_for @user_language, url: update_language_path(language_id: @user_language.id), method: :patch do |f| %>
    <%= f.input :language %>
    <%= f.input :level, collection: ["Beginner", "Intermediate", "Expert"] %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit_skill.html.erb
<div class="container mt-5 pt-5">
  <h2>Edit skill</h2>
  <%= simple_form_for @user_skill, url: update_skill_path(skill_id: @user_skill.id), method: :patch do |f| %>
    <%= f.input :skill %>
    <%= f.input :level, collection: ["Beginner", "Intermediate", "Expert"] %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/new_certification.html.erb
<div class="mt-5 p-5">
  <%= simple_form_for @user_certification, url: "/certifications" do |f| %>
  <%= f.input :certification %>
  <%= f.input :company %>
  <%= f.input :year %>
  <%= f.submit %>
  <% end %>
</div>

app/views/users/new_education.html.erb
<div class="mt-5 p-5">
  <%= simple_form_for @user_education, url: "/educations" do |f| %>
  <%= f.input :country, as: :string %>
  <%= f.input :college %>
  <%= f.input :title %>
  <%= f.input :major %>
  <%= f.input :year %>
  <%= f.submit %>
<% end %>
</div>

app/views/users/new_language.html.erb
<%= simple_form_for @user_language, url: "/languages" do |f| %>
  <%= f.input :language %>
  <%= f.input :level, collection: ["Beginner","Intermediate","Expert"] %>
  <%= f.submit %>
<% end %>

app/views/users/new_skill.html.erb
<div class="container mt-5 pt-5">
  <h2>Add a new skill</h2>
  <%= simple_form_for @user_skill, url: "/skills" do |f| %>
    <%= f.input :skill %>
    <%= f.input :level, collection: ["Beginner","Intermediate","Expert"] %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/profile.html.erb
<div class="banner profile-banner"></div>
<div class="d-flex mx-5 mt-n5">
  <% if current_user.photo.attached? %>
    <%= cl_image_tag current_user.photo.key, class: "avatar-profile border border-light border-3", alt: "user-avatar" %>
  <% else %>
      <%= image_tag("avatar_default.png", class: "avatar-profile", alt: "user-avatar") %>
  <% end %>
  <div class="d-flex align-items-center mt-5">
    <div>
      <h4 class="text-start mx-4"><%= current_user.first_name %> <%= current_user.last_name %> <%= link_to '', edit_user_registration_path, class: 'mx-1 fa-solid fa-pen-to-square text-decoration-none' %></h4>

      <p class="px-4"><%= current_user.description %></p>
    </div>
  </div> <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar-profile border border-light border-3", alt: "user-avatar" %>
</div>


<div class="container mt-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active btn btn-light" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link btn btn-light" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Services</button>
    </li>
  </ul>
  <div class="tab-content pt-3" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <div class="d-flex justify-content-between">
        <h4>Languages</h4>
        <%= link_to '', new_language_path, class: 'fa-solid fa-plus text-decoration-none text-light py-2' %>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_languages.each do |language| %>
          <div class="col-auto">
            <span><%= language.language.capitalize %></span>
            <span class="fst-italic fw-light text-white">- <%= language.level %></span>
            <%= link_to '', edit_language_path(language), class: 'mx-1 fa-solid fa-pen-to-square text-decoration-none' %>
            <%= link_to '', destroy_language_path(language), data: { turbo_method: :delete, turbo_confirm: "Do you want to proceed?"}, class: 'fa-solid fa-trash text-danger text-decoration-none ps-2' %>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Skills</h4>
        <%= link_to '', new_skill_path, class: 'fa-solid fa-plus text-decoration-none text-light py-2' %>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_skills.each do |skill| %>
          <div class="col-auto">
            <span class="mb-0"><%= skill.skill %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= skill.level %></span>
            <%= link_to '', edit_skill_path(skill), class: 'mx-1 fa-solid fa-pen-to-square text-decoration-none' %>
            <%= link_to '', destroy_skill_path(skill), data: { turbo_method: :delete, turbo_confirm: "Do you want to proceed?"}, class: 'fa-solid fa-trash text-danger text-decoration-none ps-2' %>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Education</h4>
        <%= link_to '', new_education_path, class: 'fa-solid fa-plus text-decoration-none text-light py-2' %>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_educations.each do |education| %>
          <div class="col-auto">
            <span class="mb-0"><%= education.major %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= education.college %></span>
            <span class="mb-0 fst-italic fw-light text-white">, <%= education.year %></span>
            <%= link_to '', edit_education_path(education), class: 'mx-1 fa-solid fa-pen-to-square text-decoration-none' %>
            <%= link_to '', destroy_education_path(education), data: { turbo_method: :delete, turbo_confirm: "Do you want to proceed?"}, class: 'fa-solid fa-trash text-danger text-decoration-none ps-2' %>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Certifications</h4>
        <%= link_to '', new_certification_path, class: 'fa-solid fa-plus text-decoration-none text-light py-2' %>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_certifications.each do |certification| %>
          <div class="col-auto">
            <span class="mb-0"><%= certification.certification %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= certification.company %></span>
            <span class="mb-0 fst-italic fw-light text-white">, <%= certification.year %></span>
            <%= link_to '', edit_certification_path(certification), class: 'mx-1 fa-solid fa-pen-to-square text-decoration-none' %>
            <%= link_to '', destroy_certification_path(certification), data: { turbo_method: :delete, turbo_confirm: "Do you want to proceed?"}, class: 'fa-solid fa-trash text-danger text-decoration-none ps-2' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <% unless @user_services.nil? %>
        <div class="d-flex justify-content-between mb-5 pb-5">
          <h4>Services</h4>
          <%= link_to '', new_service_path, class: 'fa-solid fa-plus text-decoration-none text-light py-2' %>
        </div>
        <div>
          <% @user_services.each do |service| %>
            <div>
              <h4 class="mb-1"><%= service.title %></h4>
              <p class="mb-1 fst-italic fw-light text-white">- <%= service.description %></p>
              <%= link_to '', edit_service_path(service), class: 'mb-3 fa-solid fa-pen-to-square text-decoration-none' %>
              <%= link_to '', service_path(service), data: { turbo_method: :delete, turbo_confirm: "Do you want to proceed?"}, class: 'fa-solid fa-trash text-danger text-decoration-none' %>
            </div>
            <hr>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner profile-banner"></div>
<div class="d-flex mx-5 mt-n5">
  <% if @user.photo.attached? %>
    <%= cl_image_tag @user.photo.key, class: "avatar-profile border border-light border-3", alt: "user-avatar" %>
  <% else %>
      <%= image_tag("avatar_default.png", class: "avatar-profile", alt: "user-avatar") %>
  <% end %>
  <div class="d-flex align-items-center mt-5">
    <div>
      <h4 class="text-start mx-4"><%= @user.first_name %> <%= @user.last_name %> </h4>

      <p class="px-4"><%= @user.description %></p>
    </div>
  </div>
</div>

<div class="container mt-5">
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active btn btn-light" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link btn btn-light" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Services</button>
    </li>
  </ul>
  <div class="tab-content pt-3" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
      <div class="d-flex justify-content-between">
        <h4>Languages</h4>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_languages.each do |language| %>
          <div class="col-auto">
            <span><%= language.language %></span>
            <span class="fst-italic fw-light text-white">- <%= language.level %></span>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Skills</h4>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_skills.each do |skill| %>
          <div class="col-auto">
            <span class="mb-0"><%= skill.skill %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= skill.level %></span>

          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Education</h4>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_educations.each do |education| %>
          <div class="col-auto">
            <span class="mb-0"><%= education.major %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= education.college %></span>
            <span class="mb-0 fst-italic fw-light text-white">, <%= education.year %></span>
          </div>
        <% end %>
      </div>
      <hr>
      <div class="d-flex justify-content-between mt-4">
        <h4>Certifications</h4>
      </div>
      <div class="row gx-5 mb-5">
        <% @user_certifications.each do |certification| %>
          <div class="col-auto">
            <span class="mb-0"><%= certification.certification %></span>
            <span class="mb-0 fst-italic fw-light text-white">- <%= certification.company %></span>
            <span class="mb-0 fst-italic fw-light text-white">, <%= certification.year %></span>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
      <% unless @user_services.nil? %>
        <div class="d-flex justify-content-between">
          <h4>Services</h4>
        </div>
        <div>
          <% @user_services.each do |service| %>
            <div>
              <h4 class="mb-1"><%= service.title %></h4>
              <p class="mb-1 fst-italic fw-light text-white">- <%= service.description %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>