config/routes.rb
Rails.application.routes.draw do
  # resources :services
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "users#profile"
  # get "/pending_orders", to: "sales#show_pending_orders"
  get "/pending_sales", to: "sales#show_pending_sales"
  get "myorders", to: "sales#my_orders"
  patch "sales/:id", to: "sales#update_status", as: "update_status"
  # get "/services/:id", to: "services#show"
  # post "services/:service_id/sales", to: "sales#create"
  get "/user_services", to: "services#user_services"
  # get "/services/new", to: "services#new"
  # get "services:id/edit", to: "services#edit"
  resources :services, only: %i[index new create edit update destroy show] do
    resources :sales, only: %i[new create]
  end
  resources :sales, only: %i[edit show]

  resources :users, only: %i[show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users/languages/new", to: "users#new_language", as: :new_language
  post "/languages", to: "users#create_language"
  get "edit_language/:language_id", to: "users#edit_language", as: :edit_language
  patch "update_language/:language_id", to: "users#update_language", as: :update_language
  delete "destroy_language/:language_id", to: "users#destroy_language", as: "destroy_language"

  get "/users/skills/new", to: "users#new_skill", as: :new_skill
  post "/skills", to: "users#create_skill"
  get "edit_skill/:skill_id", to: "users#edit_skill", as: :edit_skill
  patch "update_skill/:skill_id", to: "users#update_skill", as: :update_skill
  delete "destroy_skill/:skill_id", to: "users#destroy_skill", as: "destroy_skill"

  get "/users/educations/new", to: "users#new_education", as: :new_education
  post "/educations", to: "users#create_education"
  get "edit_education/:education_id", to: "users#edit_education", as: :edit_education
  patch "update_education/:education_id", to: "users#update_education", as: :update_education
  delete "destroy_education/:education_id", to: "users#destroy_education", as: "destroy_education"

  get "/users/certifications/new", to: "users#new_certification", as: :new_certification
  post "/certifications", to: "users#create_certification"
  get "edit_certification/:certification_id", to: "users#edit_certification", as: :edit_certification
  patch "update_certification/:certification_id", to: "users#update_certification", as: :update_certification
  delete "destroy_certification/:certification_id", to: "users#destroy_certification", as: "destroy_certification"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer py-4 mt-5">
  <div class="container">
    <div class="footer-content">
      <div class="footer-item">
        <%= image_tag "logo_fivel.png", alt: "logo", class: "footer-image" %>
      </div>
      <div class="footer-item social-icons">
        <a href="#"><i class="fab fa-facebook-f fa-lg"></i></a>
        <a href="#"><i class="fab fa-twitter fa-lg"></i></a>
        <a href="#"><i class="fab fa-linkedin-in fa-lg"></i></a>
        <a href="#"><i class="fab fa-instagram fa-lg"></i></a>
      </div>
      <div class="footer-item">
        <p class="copyright-text">&copy; 2024 Fivel. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-fivel">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo_fivel.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="p-2 nav-item"><%= link_to "Explore", services_path %></li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar mx-2", alt: "user-avatar" %>
          <% else %>
            <%= image_tag("avatar_default.png", class: "avatar mx-2") %>
          <% end %>
          <a href="#" class="bars" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-bars"></i>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "/profile", class: "dropdown-item" %>
              <%= link_to "My orders", myorders_path, class: "dropdown-item" %>
              <%= link_to "My listings", user_services_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <div class="d-flex">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-warning fw-bold" %>
              <%= link_to "Login", new_user_session_path, class: "nav-link text-warning fw-bold" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>