config/routes.rb
Rails.application.routes.draw do
  # resources :services
  devise_for :users
  root to: "pages#home"
  get "/profile", to: "users#profile"
  # get "/pending_orders", to: "sales#show_pending_orders"
  get "/pending_sales", to: "sales#show_pending_sales"
  get "myorders", to: "sales#my_orders"
  patch "sales/:id", to: "sales#update_status", as: "update_status"
  # get "/services/:id", to: "services#show"
  # post "services/:service_id/sales", to: "sales#create"
  get "/user_services", to: "services#user_services"
  # get "/services/new", to: "services#new"
  # get "services:id/edit", to: "services#edit"
  resources :services, only: %i[index new create edit update destroy show] do
    resources :sales, only: %i[new create]
  end
  resources :sales, only: %i[edit show]

  resources :users, only: %i[show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/users/languages/new", to: "users#new_language", as: :new_language
  post "/languages", to: "users#create_language"
  get "edit_language/:language_id", to: "users#edit_language", as: :edit_language
  patch "update_language/:language_id", to: "users#update_language", as: :update_language
  delete "destroy_language/:language_id", to: "users#destroy_language", as: "destroy_language"

  get "/users/skills/new", to: "users#new_skill", as: :new_skill
  post "/skills", to: "users#create_skill"
  get "edit_skill/:skill_id", to: "users#edit_skill", as: :edit_skill
  patch "update_skill/:skill_id", to: "users#update_skill", as: :update_skill
  delete "destroy_skill/:skill_id", to: "users#destroy_skill", as: "destroy_skill"

  get "/users/educations/new", to: "users#new_education", as: :new_education
  post "/educations", to: "users#create_education"
  get "edit_education/:education_id", to: "users#edit_education", as: :edit_education
  patch "update_education/:education_id", to: "users#update_education", as: :update_education
  delete "destroy_education/:education_id", to: "users#destroy_education", as: "destroy_education"

  get "/users/certifications/new", to: "users#new_certification", as: :new_certification
  post "/certifications", to: "users#create_certification"
  get "edit_certification/:certification_id", to: "users#edit_certification", as: :edit_certification
  patch "update_certification/:certification_id", to: "users#update_certification", as: :update_certification
  delete "destroy_certification/:certification_id", to: "users#destroy_certification", as: "destroy_certification"
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :status, :date, :price, :user_id, :service_id, presence: true
  validates :price, numericality: { only_float: true }
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[show edit update_status]
  before_action :authenticate_user!

  def show; end

  def new
    @sale = Sale.new
  end

  def create
    @service = Service.find(params[:service_id])
    @sale = Sale.create!(status: "pending", date: Date.today, price: @service.price, user: current_user, service: @service)
    redirect_to root_path, notice: 'Product was successfully saved.'
  end

  def edit; end

  def update_status
    if @sale.update(status: params[:status])
      redirect_to pending_sales_path, notice: 'Status was successfully updated.'
    else
      redirect_to pending_sales_path, alert: 'Failed to update status.'
    end
  end

  def my_orders
    @my_orders = current_user.sales
  end

  def show_pending_sales
    # @pending_sales = []
    # current_user.services.each do |service|
    #   service.sales.each do |sale|
    #     @pending_sales << sale if sale.status == "pending"
    #   end
    # end
    @pending_sales = Sale.joins(:service).where(services: { user_id: current_user.id }, sales: { status: "pending" })
  end

  private

  def sale_params
    params.require(:sale).permit(:status, :date, :price, :rating, :service_id)
  end

  def set_sale
    @sale = Sale.find(params[:id])
  end
end

app/views/sales/my_orders.html.erb
<div class="container">
  <h1 class="text-center my-4 pt-5">My Orders</h1>
  <table class="table table-striped table-dark custom-table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Title</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @my_orders.each_with_index do |order, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= order.service.title %></td>
          <td><%= order.status %></td>
          <td><%= link_to "Details", sale_path(order.id), class: 'btn btn-details' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sales/show.html.erb
<div class="container mt-5 pt-5">
  <div class="sale-details my-5">
    <div class="sale-header">
      <h1>Sale Details</h1>
      <p class="sale-status"><%= @sale.status %></p>
    </div>

    <div class="sale-info">
      <h2>Service: <%= @sale.service.title %></h2>
      <p><strong>Seller:</strong> <%= @sale.service.user.first_name %> <%= @sale.service.user.last_name %></p>
      <p><strong>Category:</strong> <%= @sale.service.category %></p>
      <p><strong>Description:</strong> <%= @sale.service.description %></p>
      <p><strong>Price:</strong> $<%= @sale.price %></p>
      <p><strong>Delivery Date:</strong> <%= @sale.date %></p>
    </div>
    <%= link_to 'Back to Orders', myorders_path, class: "btn-main" %>
  </div>
</div>

app/views/sales/show_pending_sales.html.erb
<div class="container">
  <h1 class="text-center my-5">My Pending Sales</h1>
  <% if @pending_sales.present? %>
    <table class="table table-striped table-dark custom-table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Title</th>
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @pending_sales.each_with_index do |sale, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= sale.service.title %></td>
            <td><%= sale.status %></td>
            <td>
              <div class="btn-group" role="group" aria-label="Actions">
                <%= button_to update_status_path(sale, status: 'accepted'), method: :patch, class: 'btn button-custom accept' do %>
                  <i class="fas fa-check"></i>
                <% end %>

                <%= button_to update_status_path(sale, status: 'cancelled'), method: :patch, class: 'btn button-custom decline' do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="container">
      <h2 class="text-center mt-5 text-muted">No pending sales :(</h2>
    </div>
  <% end %>
</div>